### PR TITLE
Added optional feedback parameters.

### PR DESCRIPTION
**Pull request by GhaziTriki**
ref #8 : it is now possible to add COMPLUS and PARAMPLUS feedback parameters

### CODE REVIEW

**Comment by coatesap** [comment]
@GhaziTriki Hi, that looks interesting. Before I merge it, could you just explain a little bit about what this feature does, and an example of how it is used (we could then also add the example to the readme)?

**Comment by GhaziTriki** [comment]
Yes of course if you take a look here : http://www.barclaycard.co.uk/business/files/ePDQ_Advanced_Integration_Guide.pdf

In page 29 it says:

The merchant can send us two extra parameters in the hidden fields of the order form, in order to
retrieve them as feedback parameter after the payment. The following hidden fields are available:
```html
<input type="hidden" name="COMPLUS" value="">
<input type="hidden" name="PARAMPLUS" value="">
```
More explanation is given in page 30

I have devoured the documentation and more pull requests are coming.

**Comment by GhaziTriki** [comment]
I will create another pull request with README update to explain how the library can be used it as it has some minor difference from the common Omnipay.

**Comment by GhaziTriki** [comment]
I have created a README udpate branch https://github.com/inhanx/omnipay-barclays-epdq/tree/readme-update

Once you merge this pull request I will update the README to explain additional parameters usage.

**Comment by GhaziTriki** [comment]
The explanation was added to readme update pull request. All pull requests are now ready to be merged. Can you please tag a new version after merging them all?

**Pull request merged**
