### PR TITLE
Split the 3 url parameters setter

### PR DESCRIPTION
**Pull request by GhaziTriki**
ref #17 : the three response back url can now be different.

### CODE REVIEW

**Comment by coatesap** [comment]
Hi Ghazi, I haven't actually tested this, but does it actually remove the ability to just set a single return url using the generic returnUrl parameter? If so, this would break many existing integrations (including mine!), and deviate away from the OmniPay principle of being able to swap between payment gateway drivers easily. One solution might be to let the setReturnUrl method just call the other methods, setting the individual urls to whatever was passed in the generic returnUrl param...

Cheers,
Andy

**Comment by GhaziTriki** [comment]
I thought about it and I was sure that it has bad implications. I like the backward compatibility fallback you have proposed and I will implement it.

**Comment by samvaughton** [comment]
Hi @GhaziTriki I have given you access to the repo so you can merge these yourself like Andy suggested. Just make sure to keep BC for @coatesap and write tests =)

**Comment by GhaziTriki** [comment]
Thank you very much. I am really grateful you have given me access to the repository.

**Comment by samvaughton** [comment]
You're welcome :+1:

**Pull request merged**
